apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-subscriptions-cm
  namespace: argocd
data:
  subscriptions: |
    - recipients:
        - github:Vikgur
      triggers:
        - on-deployed
        - on-health-degraded
