apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.health.gurko.ru
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: GITHUB_CLIENT_ID
          clientSecret: GITHUB_CLIENT_SECRET
          orgs:
            - name: vik-devops-lab
  oidc.config: |
    name: GitHub
    issuer: https://dex.argocd.svc.cluster.local:5556/dex
    clientID: argo-cd
    clientSecret: unused
    requestedScopes: ["openid", "profile", "email", "groups"]
  application.instanceLabelKey: app.kubernetes.io/instance
  resource.customizations.health.argoproj.io/Rollout: |
    hs = {}
    hs.status = "Healthy"
    hs.message = rollout.status
    return hs
  timeout.reconciliation: 180s
  timeout.hard.reconciliation: 300s
